add_newline = true

[directory]
truncation_length = 100
truncate_to_repo = false

[character]
symbol = "ğŸº"

[aws]
style = "bold blue"
symbol = "ğŸ…° "
displayed_items = "all"

[aws.region_aliases]
ap-northeast-1 = "jp"

[memory_usage]
disabled = false
show_percentage = false
show_swap = true
threshold = -1
symbol = ""
separator = "/"
style = "bold dimmed blue"

[docker_context]
disabled = false
only_with_files = false
symbol = "ğŸ‹ "

[git_commit]
truncation_length = 4

[time]
disabled = false
format = "ğŸ•™[ %T ]"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"

