add_newline = true

[directory]
truncation_length = 100
truncate_to_repo = false

[character]
symbol = "$"

[package]
disabled = true

[aws]
style = "bold blue"
symbol = "ğŸ…° "
displayed_items = "all"

[aws.region_aliases]
ap-northeast-1 = "jp"

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
symbol = ""
separator = "/"
style = "bold dimmed blue"

[docker_context]
disabled = true
only_with_files = false
symbol = "ğŸ‹ "
